### ISSUE TITLE
Conflict with Active Admin

### ISSUE THREAD

**Issue by aarellano** [the-teacher/the_role#42]
I'm trying to use `the_role` in my rails 4.0.2 app, but after I add the gem into my Gemfile, I get the following error message when trying to run any `rails` command:

```
activesupport-4.0.2/lib/active_support/dependencies.rb:464:in `load_missing_constant': 
Unable to autoload constant Base, 
expected /opt/boxen/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_role-2.3/app/models/concerns/base.rb 
to define it (LoadError)
```

Any ideas?

**Comment by the-teacher** [comment]
TODO: Check it with AA

## Attention! Last stable 2.X version can be installed with

```ruby
gem 'the_role',
  github: 'TheRole/TheRoleApi',
  tag: 'v2.6'
```

**Right now we working on TheRole 3.0**

**Comment by the-teacher** [comment]
I hope this problem was fixed in new version. But I'm not sure

===

Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!

**Comment by urHuckleberry1** [comment]
Citizen Code Of Conduct
Suitable for large communities and events
