### ISSUE TITLE
Model name isn't configurable?

### ISSUE THREAD

**Issue by vebersol** [the-teacher/the_role#58]
I was reading the code to find a solution for my issue. I'm using the_role as a role manager on my model that is called Admin.

Then, when I try to delete one role, it returns the following error:

> ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: people.role_id: SELECT  1 AS one FROM "people"  WHERE "people"."type" IN ('User') AND "people"."role_id" = ?
LIMIT 1

Since my model is admin it should be admins.role_id, isn't that right?

I see that the relationship is set on this file (line 21):

https://github.com/the-teacher/the_role/blob/master/app/models/concerns/role.rb#L21

My question is: there's a non documented way to do that or may it being not defined as I expect?

Thanks in advance,
Vinícius Ebersol

**Comment by the-teacher** [comment]
Sorry, but it still unconfigurable.
I'll add it to new roadmap.

=== 

Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!
