### ISSUE TITLE
`create_section': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by archick12** [the-teacher/the_role#60]
HI!
I am receiving:
.rvm/gems/ruby-2.1.0/gems/the_role-2.5.4/app/models/concerns/role.rb:58:in `create_section': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/system/.rvm/gems/ruby-2.1.0/gems/the_role-2.5.4/app/models/concerns/role.rb:65:in `create_rule'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/the_role-2.5.4/lib/generators/the_role/the_role_generator.rb:51:in `create_admin_role'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/the_role-2.5.4/lib/generators/the_role/the_role_generator.rb:14:in `generate_controllers'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `each'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `invoke_all'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/generators.rb:156:in `invoke'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/generate.rb:11:in `<top (required)>'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
        from /home/system/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:48:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

When I am trying to execute: bundle exec rails g the_role admin
I was following steps from README and tried to update my existing project.
Any ideas?

**Comment by the-teacher** [comment]
## Attention! Last stable 2.X version can be installed with

```ruby
gem 'the_role',
  github: 'TheRole/TheRoleApi',
  tag: 'v2.6'
```

**Right now we working on TheRole 3.0**
