### ISSUE TITLE
The rule for admin role is empty

### ISSUE THREAD

**Issue by petermumford** [the-teacher/the_role#63]
I've followed your instructions to get 'the_role' fully installed. Everything went smoothly until I did `rails g the_role admin` The rule is created in the database but `the_role` attribute is empty, no json string. Below is the log from console:

`=> #<Role id: 1, name: "admin", title: "role for admin", description: "this user can do anything", the_role: {}, created_at: "2014-06-11 14:11:57", updated_at: "2014-06-11 14:11:57">`
`irb(main):031:0> r.the_role
=> {}`

I'm assuming `the_role` should show with the below json string? I've tried creating the rule again and nothing changes. Is there anything I can try to get this working?

`{
  :system => {
    :administrator => true
  }
}`

Rails 4.1.1
jRuby 1.7.9
Postgresql 9.3.4

**Comment by the-teacher** [comment]
## Attention! Last stable 2.X version can be installed with

```ruby
gem 'the_role',
  github: 'TheRole/TheRoleApi',
  tag: 'v2.6'
```

**Right now we working on TheRole 3.0**
