### ISSUE TITLE
Several Issues - the instructions say one thing generator does another 

### ISSUE THREAD

**Issue by rbyrns** [the-teacher/the_role#66]
The Role model on the tutorial -  include TheRole::Role . However if you use the generator it makes it RoleModel::Role .  

In my own app, I am getting errors like - NameError: uninitialized constant TheRole::AdminRoutes .  Adding admin refuses to work.  Again the db has the field the_role (text) and just id as the unique.  Should it be role_id?
Installing the dummy program does not work as described because of issues with the_role_bootstrap3_ui not found in the repository.  sprockets also throws errors from bundle.
I am too new to rails to figure all this out, but I have checked the instructions close.
I am using rails 4.1.6  and MySql.  I am going through it one more time from the beginning to get the first trace to post here as soon as I can.

**Comment by the-teacher** [comment]
I will check it later

## Attention! Last stable 2.X version can be installed with

```ruby
gem 'the_role',
  github: 'TheRole/TheRoleApi',
  tag: 'v2.6'
```

**Right now we working on TheRole 3.0**

**Comment by the-teacher** [comment]
Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!
