### ISSUE TITLE
undefined method `authenticate_user!'

### ISSUE THREAD

**Issue by vtrkanna** [the-teacher/the_role#67]
Hi

I'm facing issue 

http://0.0.0.0:3000/admin/roles/new

NoMethodError (undefined method `authenticate_user!' for #<Admin::RolesController:0x00000005ead968>):
  the_role (2.5.4) app/controllers/concerns/controller.rb:4:in`login_required'

**Comment by vtrkanna** [comment]
Hi

When we are running dummy app, we are facing json loading issue.

     /home/user/.rvm/gems/ruby-2.1.2@dummy_app/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- multi_json (LoadError)

**Comment by the-teacher** [comment]
rails 4.2 ? Hm. I need few days to check TheRole with rails 4.2 
Right now I don't know where is a problem.
Try to downgrade to rails 4.1.x

**Comment by the-teacher** [comment]
and try to use master branch
I have some commits in august

https://github.com/the-teacher/the_role/commit/62b5e403b3f2d102c0dfeafcbc17519bd6576be2

it can be helpful
