### ISSUE TITLE
I18n::MissingTranslationData in Admin::Roles#index

### ISSUE THREAD

**Issue by ghost** [the-teacher/the_role#71]
After follow the installation instruction for GUI manage roles,, when I try to access the /admin/role page, i have this error (show the title of this issue).
error log show me:
"Showing /home/jerome/.rvm/gems/ruby-2.2.2/gems/the_role_management_panel-3.0.2/app/views/admin/roles/_sidebar.html.haml where line #11 raised:"
" translation missing: en.admin.roles.sidebar.roles_list"
and from line 311:
"        raise exception.respond_to?(:to_exception) ? exception.to_exception : exception"
Trace of template inclusion: /home/jerome/.rvm/gems/ruby-2.2.2/gems/the_role_management_panel-3.0.2/app/views/admin/roles/index.haml

**Comment by the-teacher** [comment]
@jerome2  thanks for report! Can you try add missing translation in your App locale? I will check it today.

**Comment by jerome2** [comment]
for resolve the problem, one way could be to just add in 'config/locales/en.yml' files the entries needed for translate the asked titles (follow yaml convention and just add informations needed by the view)
exemple: 
en:
  hello: "Hello world"
  admin:
    roles:
      sidebar:
	roles_list: "Roles list"
(and do it for each error ask for translate missed data in this locale file)

Maybe an other way could be to add a function in the gem 'the_role' for add these data (depend of the langage... it could not be full answer for all of us), or maybe talk of that point on the GUI installation instruction page.
Thanks for this gem, it is really good gem for use roles with devise gem.

**Comment by irridescentrambler** [comment]
In my config/locales/en.yml

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
