### ISSUE TITLE
unable to open selection from comboBox for enable/disable a rule

### ISSUE THREAD

**Issue by jerome2** [the-teacher/the_role#72]
under firefox-38.0.5 from archlinux, i can not use the comboBox for enable a new rule.
This is from the GUI admin Role page. is it from bootstrap and how to find information for fix/resolve the problem ? (i read something around dropdown function who is not same interprted by web  browsrs engines... but i think from css and javascript, it could be possible to add codes to take care so many different un-standardised way of thinking for all of them)
Also, i installed chromium... same problem occurs.
Opera just don't want to show me localhost:3000 (i directly uninstall it quickly).
And Microsoft IE or Safary Apple... i really don't want to touch this anymore and i will not. :)
thank you.

**Comment by the-teacher** [comment]
very strange

**Comment by the-teacher** [comment]
Can you test it with original Dummy App?

https://github.com/TheRole/DummyApp

Can you reproduce this bug with Dummy App?

**Comment by jerome2** [comment]
i clone and test it.
now the GUI works fine with dropdown functions.
i just do it now, so i will take time to check why (check the gem list and versions used and also the reference called on configs files), then i will go back to tell you what's my error or what's the error could happen (if come from a lake inside the doc).
thanks again for your quick answer.

**Comment by jerome2** [comment]
Ok, consider that the updates (i think bootstrap-sass and jquery-rails maybe) resolve this problem.
My web-browser was keep the old one and refresh pages wasn't suffisant for hang the change on this point.
Thanks.

**Comment by jerome2** [comment]
Find the problem:
i had a bootstrap.js.coffee file in the assets/javascript directory (i think installed by rails-coffee) who mounted up the bootstrap function needed by bootstrap-sass.
the content was:
jQuery ->
  $("a[rel~=popover], .has-popover").popover()
  $("a[rel~=tooltip], .has-tooltip").tooltip()

remove this file solve this problem (and hope not occur an other one with coffeescript code...)
problem is solved and definitly not from your gem code.
thanks.
