### ISSUE TITLE
an error when try to ask for admin role

### ISSUE THREAD

**Issue by jerome2** [the-teacher/the_role#73]
in the doc i see it with rails c (and works):
After update the first user as admin (role_id becomes 1)
User.first.admin?
=> true 
After update the user number 34 as admin role
User.find(34).admin?
=> false
but... the user with id 34 is an admin and in the database the role_id is 1 (so i see the update pointed on User.find(34) worked).
is it normal (i think not) and/or what i forget ?
i use database postgresql-9.4.4 (but normal id system, no uuid used). I see .find (ids) method from activeRecord works fine, so... maybe not from gem pg nor ActiveRecord.
Do you have an idea in case of this is not normal ?

**Comment by jerome2** [comment]
I also see that there is inside the SQL call (at the end) a "LIMIT 1". Then for sure, i can not have an other one admin than this one is the first: id = 1. I think this is the way for understand what's happen, maybe it is normal and i miss a part of the doc around that and how to remove this limitation. could you tell me please ?

**Comment by jerome2** [comment]
also, on your DummyApp test application, seems to just works fine on this point.
but, it used sqlite instead of postgresql (that is the difference i was able to see).
(i have to touch a view file because add a new user by sign up will crash the application when call root page after that... in fact, i don't know why, it could be possible to sign up before sign out... there is an autologin macro... then i have to add in the condition of the user form in the layout part to check that current_user.role wasn't null, and add the sign out link to be able to sign out in the else condition)
After add the nex user and give him the admin role, this works has attempted in your DummyApp test. But i can not at this time point where is the error in mine (i follow the doc, but i add also the_comments gem... and remove cancancan AFTER install your gem).
I will check more...

**Comment by the-teacher** [comment]
please show me

```ruby
User.find(34).role.to_hash
```

**Comment by jerome2** [comment]
=> {"system"=>{"administrator"=>true}}

**Comment by the-teacher** [comment]
hm. looks fine. hm. I am not at home right now, I check it when I come back

**Comment by jerome2** [comment]
find the problem:
i had some code inside the user.rb model (when follow installation from your the_comments gem) who mount admin? member function... then that is why this can not be more works after that. So i try to change the code for give back all admin users:
instead of "self == User.first"
i try
"self==User.where(role_id: 1).take"
but not more.
So just remove all of this def around admin? inside this model user resolve this problem.
i hope not interfer on use of the_comments (if yes, we will find a solution)
so the_role has no issue. if you want, i will post an issue on the_comments (because it is him who make an error when follow the doc) ?
thanks

**Comment by the-teacher** [comment]
Is first user admin? yes, it is.

```ruby
[1] pry(main)> User.first.admin?
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 3]]
=> true
[2] pry(main)> User.first.role.to_hash
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 3]]
=> {"system"=>{"administrator"=>true}}
```

is last user admin? no.

```ruby
[4] pry(main)> User.last.id
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
=> 7

[5] pry(main)> User.last.admin?
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 1]]
=> false

[7] pry(main)> User.last.role.to_hash
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 1]]
=> {"pages"=>
  {"index"=>true, "show"=>true, "new"=>true, "create"=>true, "edit"=>true, "update"=>true, "destroy"=>true, "my"=>true, "secret"=>false}}
```

how to make last user admin

```ruby
[8] pry(main)> u = User.last
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1

[9] pry(main)> u.role = Role.with_name(:admin)
  Role Load (0.2ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = 'admin'  ORDER BY "roles"."id" ASC LIMIT 1
=> #<Role:0x007fcedf7abf88
 id: 3,
 name: "admin",
 title: "Role for admin",
 description: "This user can do anything",
 the_role: "{\"system\":{\"administrator\":true}}",
 created_at: Sun, 21 Jun 2015 11:33:12 UTC +00:00,
 updated_at: Sun, 21 Jun 2015 11:33:12 UTC +00:00>

[11] pry(main)> u.save
   (0.2ms)  begin transaction
  SQL (0.6ms)  UPDATE "users" SET "role_id" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["role_id", 3], ["updated_at", "2015-06-21 11:38:54.858279"], ["id", 7]]
   (9.0ms)  commit transaction
=> true

[12] pry(main)> User.last.admin?
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 3]]
=> true

[13] pry(main)> User.last.role.to_hash
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 3]]
=> {"system"=>{"administrator"=>true}}
```

test it again with another way

```ruby
[14] pry(main)> User.last.has_role? :administrator, :admin
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Role Load (0.1ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."id" = ? LIMIT 1  [["id", 3]]
=> true
```

I can't understand where is your problem. It can be related with you application code

**Comment by jerome2** [comment]
@the_teacher: i think you not read all my post or maybe i'm not clear in my formulation.
If you install the_role and the_comments and follow exactly the doc for do it, my answer to your first question is:

1 No, absolutly not, first user is admin only if you decide and be able to do it, it is a convention but this is also a usage limitation (so a "non-constructive" convention in this case). If you add the gem when the database table users has allready some other users, the id is no more 1 when you add a user, so it could be not the first one.
2 Then if you want also to have more than only one admin user, it would be the same problem in this specific case.

this 2 arguments just show what is the problem to add this code in user.rb model when mix gem 'the_role' and gem 'the_comments'.

So again: add the_comments inside your DummyApp, then just do it by follow your doc for 'the_comments', and go to your rails console for check... you will see it and will understand what i talk you about.

You can try and test it yourself, but i done it and i just give you back my observation (i hope this can help to point what is a problem for use them together with this code added in user.rb file i think).

Tell me when we talk about the same and/or when you will understand what is the problem (or telle where i'm wrong).

**Comment by the-teacher** [comment]
I think this example have to solve your problem. Isn't it?

```ruby
class User < ActiveRecord::Base
  devise :database_authenticatable,
    :confirmable,
    :recoverable,
    :validatable,
    :registerable,
    :rememberable,
    :omniauthable,
    :omniauth_providers => %w[
      facebook
      twitter
      vkontakte
      google_oauth2
      odnoklassniki
    ]

  include TheRole::User

  # TheComments methods
  def comments_admin?
    self.admin?
  end

  def comments_moderator? comment
    self.moderator?(:comments)
  end
end
```

**Comment by jerome2** [comment]
yes, comment_admin? member function is fine to add...
you are simply the best.
very good.
thanks again
