### ISSUE TITLE
No route matches [PATCH] "/admin/roles/1/change"

### ISSUE THREAD

**Issue by ghost** [the-teacher/the_role#74]
When try to edit a role, for exemple, edit the title of the role from the admin role page, when submit (clic the green button for update the edition of the title), this error occur.
This occur also on your DummyApp application test.

**Comment by jerome2** [comment]
i look at the code, coffeescript (the_role_editinplace.js.coffe) code from button works fine (send the submit), but i suspect something on the controller 'roles_controller.rb' on ""change" member function, and/or on the view _role.html.haml on line 17. But my level on Rails is not good, so i can not be able to fix this. I see on the route list there is no PATCH method, but PUT method instead.
I need to learn more about render call conventions with Rails.

Maybe this could help to see and try to resolve.

**Comment by jerome2** [comment]
find the solution:
just add at line 17 on file _role.html.haml (inside the gem the_role_management_panel-3.0.2, at app/views/admin/roles/):
method: :put 
this argument inside the form_for will works for update.
i don't know why, but the submit with this form automaticly choose method patch instead, but the route is not indicate.
Maybe an other solution could be to do something inside the route.rb on same gem app... but i think indicate the method to 'put' will be the easy way.
after that, this error is resolved.

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
