### ISSUE TITLE
Uncaught TypeError: a_item.hide(...).off is not a function

### ISSUE THREAD

**Issue by dongalor** [the-teacher/the_role#76]
in_place editor of roles is not working

Uncaught TypeError: a_item.hide(...).off is not a function

**Comment by the-teacher** [comment]
hello.

please let me know about
1) your version of gem
2) version of rails
3) version of JQuery

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
