### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by zer0flag** [the-teacher/the_role#77]
Anyone working on a Rails 5 compatibility? As far as I can see there are only some deprecation warnings but not sure if that's all? Many thanks!

**Comment by the-teacher** [comment]
@zer0flag hello. I think it should works. But I didn't test it

**Comment by kai-breitbarth** [comment]
No it doesn't. There are several dependencies to Rails 4. 
`s.add_runtime_dependency 'rails', ['>= 3.2', '< 5']`

And it is even written in the source code
```
if Rails::VERSION::MAJOR == 5
      raise Exception.new("TheRole 3. Version for Rails 5 not tested yet")
end
```

**Comment by the-teacher** [comment]
@kai-breitbarth actually it should be ready, just some lines of code should be updated and that is all.

**Comment by the-teacher** [comment]
Rails 5 supported:

https://rubygems.org/gems/the_role/versions/3.5
https://rubygems.org/gems/the_role_api/versions/3.5
https://rubygems.org/gems/the_role_management_panel/versions/3.5

Tested manually with https://github.com/TheRole/rails5dummy
