### ISSUE TITLE
Migrating existing app to TheRole

### ISSUE THREAD

**Issue by Svashta** [the-teacher/the_role#78]
Hi,

i need some help understanding how TheRole is working.
I have an application with:

- devise
- cancancan
- rolify

This application is also multi-tenant, so each company account has many users.
There is an increasing need of company administrators to define their custom roles and set permissions to their users.

So, currently I have a predefined list of roles (admin, manager, user) with predefined permissions.
I was looking around what would be the best way to implement administrator defined roles /permissions and I found out TheRole gem which looks promising.

I basically have 2 general questions:

- what do i need to do to replace cancancan/rolify with TheRole (devise so of course stay)
- is it possible to integrate the role management panel with my own skin

I don't need very detailed information, but a general view on how to approach this problem of replacing current situation with the gem. What are the gotchas, where can problems arise.

Thanks for any reply!

**Comment by the-teacher** [comment]
@Svashta Hello, Mitja!

> is it possible to integrate the role management panel with my own skin?

yeah. that is why the solution was split into a few parts. To provide another view you can fork this gem https://github.com/TheRole/the_role_management_panel and rework it completely. You can use any CSS, JS solution to provide required view of management panel. Any changes in View part will not affect backend part of TheRole gem. Feel free to change anything in a view part of the solution.

Also Rails provides a way to define places where App looks for view templates and css/js assets. You can use the original gem `https://github.com/TheRole/the_role_management_panel` and redefine all view files. 

Please take a look at docs for `config.assets.paths` and `prepend_view_path`

```ruby
MyRailsApp::Application.config.assets.paths.unshift("#{Rails.root}/#{app/assets/}")
```

```ruby
if respond_to?(:prepend_view_path)
  prepend_view_path "PATH_TO_ALTERNATIVE_VIEWS"
end
```

> what do i need to do to replace cancancan/rolify with TheRole (devise so of course stay)

- ready the docs for TheRole https://github.com/TheRole/docs
- create a small test app to play with TheRole and analyze how it works. This one test app will be a good help for you https://github.com/TheRole/rails5dummy 

### My personal practice

I'm pretty sure TheRole is amazing solution for my own purposes. And any another gem will be amazing if you know how to use it.

But, you know, I think, the best solution is the simplest solution. I've seen many huge Rails apps for really huge companies, and you know, usually the best way to manage permissions is just to have a field in a database like this:

```ruby
User.role = "user" # manager | admin | editor
```

```ruby
class User
  def admin?
     role == "admin"
  end

  def editor?
     role == "editor"
  end

  def manager?
     role == "manager"
  end
end
```

Feel free ask any question and Good luck!
