### ISSUE TITLE
Postgres and the role

### ISSUE THREAD

**Issue by melsatar** [the-teacher/the_role#79]
I followed the documentation you mentioned about the migration and also for Postgres SQL, while when putting this code in role model

`def _jsonable val
    val.is_a?(Hash) ? val : JSON.load(val)
  end

  def to_hash
    begin the_role rescue {} end
  end

  def to_json
    the_role.is_a?(Hash) ? the_role.to_json : the_role
  end`

It keeps looping and redirecting in my applications, while it makes all my test cases pass If I removed it, the application runs normally and most of the test cases failed. should I change the_role field to JSON as well or keep the current setup. I used to use version 2.3

another issue that edit in place is not working and it says this message

`No route matches [PATCH] "/admin/roles/4/change"`

I followed the route migrations steps, but this does not work with me, any solution

**Comment by the-teacher** [comment]
@melsatar hey! Hello!
I didn't check this gem for a long time.
Could you please send me more information about your environment? ruby version, rails version, bundler version and PSQL version?

**Comment by melsatar** [comment]
Hi,

Thank you for your quick reply, Ruby 2.2.6 and rails 4.2.7 pg 0.19.0 and bundler 1.14.4
and I am using latest Postgres 9.1 most probably. but I did not change Postgres itself. I was performing migration from ruby 1.9.3 on rails 4.0.1 to the current version

Thank you

**Comment by the-teacher** [comment]
@melsatar I'll try to check this set of the tools, but you know, right now I have really busy days, it could take a while. I can't promise you a fast response about it. Sorry for that

**Comment by melsatar** [comment]
When do you expect to check that?

**Comment by the-teacher** [comment]
@melsatar maybe just on this weekend

**Comment by melsatar** [comment]
Hey, did you discover what is the issue?

:)

**Comment by the-teacher** [comment]
@melsatar hey, hello and sorry for delay!


1. Please, go to the demo app
    https://github.com/TheRole/DummyApp
2. Switch to branch `rails_4.2.7` (https://github.com/TheRole/DummyApp/tree/rails_4.2.7)
3. Change `config/database.yml`
4. And do what you you will find in README

    ``` 
    RAILS_ENV=test rake db:bootstrap
    RAILS_ENV=test rspec --format documentation
    ```

App and gem works fine. It makes me believe everything is fine with this gem.

Please, check how demo app works. It's a really simple app, and you will find everything what you need.

Don't forget to check  how routing works. https://github.com/TheRole/DummyApp/blob/rails_4.2.7/config/routes.rb#L5

Please, run tests and tell me if you will find any issues.

**Comment by the-teacher** [comment]
Expired
