### ISSUE TITLE
The title of The Roles admin page shows "TheRoleTestcase"

### ISSUE THREAD

**Issue by Beartech** [the-teacher/the_role#80]
The management panel has a fixed title of "TheRoleTestcase". Very minor but kind of annoying. Maybe have it pick up it's title from the calling application's title? Also with Rails now allowing controller specific style sheets maybe have the install of TheRole make a blank stylesheet called the_role.scss in the stylesheets directory so that specific styles can be applied to the management panel? The management panel could use some ID's on the divs to allow further personalization. 

I would be willing to work on these if you are open to the changes.

**Comment by the-teacher** [comment]
@Beartech hello! Thanks! If you want to help - you are welcome!
Than you for you feedback!

**Comment by Beartech** [comment]
I submitted a pull request for the_role_management_panel. That is were the divs reside. Also the title was fixed but the version of the_role_management_panel on GitHub is ahead of the version on rubygems.com.

**Comment by the-teacher** [comment]
@Beartech hey! Hello! 

gems were improved and updated

* https://rubygems.org/gems/the_role
* https://rubygems.org/gems/the_role_api
* https://rubygems.org/gems/the_role_management_panel

Manual testing with

* https://github.com/TheRole/DummyApp
* https://github.com/TheRole/rails5dummy

Shows gem works well.
I think there are some issues with specific environments [Test Cases](https://travis-ci.org/TheRole/DummyApp) But in general it must be ok.

⚠️  I replaces HAML templates with SLIM templates. Probably you have to add `haml-rails` into your project if you use HAML as a main template lang.

Please let me know about any issues. I will try help asap. Thanks!
