### ISSUE TITLE
rails-5, ruby-2.4

### ISSUE THREAD

**Issue by jerome-diver** [the-teacher/the_role#81]
Hi the_teacher,

Do you plan to investigate for make running this best role application to work with rails-5 and ruby-2.4 ?

**Comment by Beartech** [comment]
Just a head's up, I am currently running the_role on Rails 5.1 and Ruby 2.6.6 without any problems. I would like to upgrade to Rails 5.2 but I have modified my install as detailed elsewhere to run a custom role for each user. That meant adding a user_id column to :roles table. But it conflicts with a built in relation in the the_role_api :user model. So not sure how I am going to solve it.

**Comment by the-teacher** [comment]
Hello guys!

For 3+ years I'm not a ruby developer anymore.
It was a fantastic adventure and I enjoyed a lot, but I do not think I will be back to developing something in ruby.
I still really love the language and the eco system, but I just do not have time to focus on it. I'm sorry.

I really respect you still using something I'v been creating some time ago. Thank you for it!

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
