### ISSUE TITLE
Not an issue, but a possible fork?

### ISSUE THREAD

**Issue by Beartech** [the-teacher/the_role#82]
Not having any issue, love this gem! But we found we needed more fine grained access control lists per user. So I added a user_id to my roles table in the DB, then in the model I used:
`belongs_to :user`
Now every user has their own role. I also added a set of base permissions and various permissions that can be chosen from a web page and applied to the user's role. When I have some time I will fork the_role and show my work. I'm wondering if you would like to look at it and see if you would want to incorporate it as a feature in the_role so it could be used either way natively?

**Comment by the-teacher** [comment]
@Beartech Hey man! For last 2 years I've been writing just a front end code. JS, Node, React and all this stuff^ you know. I didn't touch my ruby projects for a while. Even not sure if I still know ruby 😄
I'm really sorry but for now I'm not going to back to all this stuff and try to support it again. Just have no time and strength. Please forgive me. I'm skipping.

**Comment by the-teacher** [comment]
@Beartech you have to know I'm really proud that someone still use it. You are really cool man! Good luck!

**Comment by Beartech** [comment]
Well I won't be abandoning it any time soon. Maybe I could become a maintainer?

**Comment by the-teacher** [comment]
@Beartech I'm happy with that. Would be nice if we could have a talk and discuss a road map and what and how you want to implement. What is better to you to be in contact skype, telegram, viber another messenger?

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
