### ISSUE TITLE
cannot load such file -- the_string_to_slug (LoadError)

### ISSUE THREAD

**Issue by i-jinshan** [the-teacher/the_role#84]
thanks for your gem, it works well in my old projects. but when i upgrade the ruby version to 2.6.3, when i run rails s ,this error happend, i don't known how to fix it.

**Comment by the-teacher** [comment]
@i-jinshan Hello! Sorry I didn't do something for open source for a while.
And didn't touch ruby more about 3 years. Can't maintain it right now.

But I'm ready to accept any PR if you have.
You are welcome to help.

Thank you!

**Comment by the-teacher** [comment]
I think a last version of the gem is here

https://github.com/the-cocoon/to_slug_param

**Comment by the-teacher** [comment]
The most recent versions of the_role_api and to_slug_param supports rails 3, rails 6, rails 7
Code is available on the repos.

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a stand-alone application.
