### ISSUE TITLE
Planing to support rails 7?

### ISSUE THREAD

**Issue by TonGarcia** [the-teacher/the_role#85]
While I was trying to install it on a rails 7 project I got the message bellow:
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 7.0.4)

    the_role (~> 3.9) was resolved to 3.9.0, which depends on
      the_role_api (= 3.9.0) was resolved to 3.9.0, which depends on
        rails (< 7, >= 3.2)
```

**Comment by the-teacher** [comment]
@TonGarcia sorry, I didn't write any ruby code for last 4 years. I do not think I have any reason to return. Just have no time for it. I'm really sorry.

**Comment by the-teacher** [comment]
@melsatar I'm going to update the gem and support rails 6/rails 7
But it will take some time. I'm trying to find some time for it. Currently very busy

**Comment by melsatar** [comment]
Hello,I thought you were about to finish it, last time you said 3 weeks since a month now :)Thank you for your support. I believe this will benefit lots of people. It would be great if you share any time expectations.Mohamed SamiSent from my iPhoneOn May 21, 2023, at 11:31 PM, Ilya N. Zykin ***@***.***> wrote:﻿
@melsatar I'm going to update the gem and support rails 6/rails 7
But it will take some time. I'm trying to find some time for it. Currently very busy

**Comment by the-teacher** [comment]
It will take time. But I'm on this way. No any estimations for now.
https://github.com/TheRole/the_role_dev

**Comment by melsatar** [comment]
It would be great if you can share some estimation, hopefully to plan other activities based on that

**Comment by the-teacher** [comment]
@melsatar Hi sir! No plans or estimations. I'm full of my mine full time job and some side projects.
I didn't touch rails or and this project for years. And also I do not have partners on this project. I do my bests

**Comment by the-teacher** [comment]
Updates are visible here. https://github.com/TheRole/the_role_dev

**Comment by melsatar** [comment]
@the-teacher 
I think if you can make sure that it bypasses the rails 5 restriction first, it may work as this is the main issue, I can help if this will make it faster. I believe this is the main update required.

As currently, rails 5 has lots of vulnerabilities and it is not supported anymore. So, I have three solutions, the first is waiting but I do not have the time frame, the second is to try to use the gem without installing it (not sure if this will work), the third is to migrate to another gem, which will be very time-consuming.

So, if you know how to use the gem files without installing them would be great, this can make me bypass the rails upgrade issue.

**Comment by the-teacher** [comment]
@melsatar I'm building a development community for the project, because I'm not able to manage everything myself.
You can leave you ideas and requests in issues here -- it will give project's members things to do.

https://github.com/TheRole/the_role_dev

**Comment by melsatar** [comment]
I copied the gems actually inside the project to call the gems locally and changed the dependencies and part of the code in other gem and it worked fine with rails 6.1Mohamed SamiSent from my iPhoneOn Jul 5, 2023, at 12:18 PM, Ilya N. Zykin ***@***.***> wrote:﻿
@melsatar I'm building a development community for the project, because I'm not able to manage everything myself.
You can leave you ideas and requests in issues here -- it will give project's members things to do.
https://github.com/TheRole/the_role_dev

**Comment by the-teacher** [comment]
backend part of `TheRole` is compatible with `Rails 6` and `Rails 7`

- [to_slug_param](https://github.com/TheRole/to_slug_param)
- [the_role_api](https://github.com/TheRole/the_role_api)

https://github.com/TheRole/the_role_dev

<img width="1125" alt="Screenshot 2023-07-06 at 16 33 45" src="https://github.com/the-teacher/the_role/assets/496713/12502b37-503d-461a-bf11-624919936ab2">

**Plan:** Frontend part will be reworked with new technologies and dockerized. It will be an independent Rails 7 Application.

**Comment by the-teacher** [comment]
Better later then never. 🤣

**Comment by melsatar** [comment]
It is working with the old one, I did not need to change the front end honestly.Good that you are working on this, I may consider reusing it again after you finish ;) Mohamed SamiSent from my iPhoneOn Jul 6, 2023, at 4:39 PM, Ilya N. Zykin ***@***.***> wrote:﻿
Better later then never. 🤣

**Comment by the-teacher** [comment]
The most recent versions of `the_role_api` and `to_slug_param` supports `rails 3`,  `rails 6`, `rails 7`
Code is available on the repos. 

https://github.com/TheRole/the_role_dev

Front-end (admin interface) part will be reimplemented soon with using Rails 7 and containerization, and published as a `stand-alone` application.

**Comment by melsatar** [comment]
@the-teacher, how to use that as a gem from the dev repo? can you register it as a gem update?

**Comment by the-teacher** [comment]
@melsatar 

In this repo you can see the most recent hashes of related gems:
https://github.com/TheRole/the_role_dev

<img width="285" alt="Screenshot 2023-07-17 at 11 27 44" src="https://github.com/the-teacher/the_role/assets/496713/7bedfcd2-bbed-43d1-abbb-c79fa50a2946">

Currently gem's tests are green for: **Rails 3,4,5,6,7**

<img width="655" alt="Screenshot 2023-07-17 at 11 28 37" src="https://github.com/the-teacher/the_role/assets/496713/d9096d71-41e6-4aa9-8be2-71599d3cc628">

To install related gems you can use a thing like that:

```
gem 'foo', git: 'git@github.com:dideler/foo.git', ref: '4aded'
```

**Gemfile.lock**

```
gem 'to_slug_param', git: 'git@github.com:TheRole/to_slug_param.git', ref: '35bf5adfc'
gem 'the_role_api', git: 'git@github.com:TheRole/the_role_api.git', ref: '1b7cdb8'
```

Updating of the rubygems version is in plans for the next week or two.
